name: "{{SERVICE}}"

on:
  push:
    paths:
      - "./{{SERVICE}}/**"
      - ".github/workflows/{{SERVICE}}.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: /- 
          ls
          cd {{SERVICE}}
          npm install


      - name: Run tests
        run: |-
          cd {{SERVICE}}
          npm test