openapi: 3.0.3
info:
  title: Ecomm - Order
  description: API to create and search for orders of the Order API
  version: 0.0.1
paths:
  /api/orders:
    post:
      summary: Creates a new order.
      description: Receives a new order and saves it in the database.
      requestBody:
        content:
          application/json:
            schema:   
              $ref: "#/components/schemas/Create-Order"
      responses:
        201: 
          description: Order successfully created!
        400: 
          description: ERROR! Could not completed the order.
  /api/orders/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      summary: Searches for an order
      description: Searches for a specific order using its ID as a parameter
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        404:
          description: Order not found
          content:
            application/json:
              example: "Not Found"
  /api/orders/{id}/confirm/{paymentId}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    - name: paymentId
      in: path
      schema:
        type: number
      required: true
    patch:
      summary: Confirms an order
      description: Confirms an order using a valid payment 
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Confirm-order-response"
        404:
          description: Order does not exist
          content:
            application/json:
              example: This order does not exist
        400:
          description: Client does not exist or payment could not be confirmed
components:
  schemas:
    Create-Order:
      type: object
      properties:
        customerId: 
          type: string
        deliveryAddress:
          type: object
          properties:
            street:
              type: string
            number:
              type: string
            complement:
              type: string
            district:
              type: string
            cep:
              type: string
            city:
              type: string
            uf:
              type: string
        items:
          type: array
          items:
            type: object
            properties:
              id: 
                type: string
              name:
                type: string
              quantity: 
                type: integer
              discount: 
                type: number
              unitPrice: 
                type: number
    Order: 
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: string
            status:
              type: string
        - $ref: "#/components/schemas/Create-Order"
    Confirm-order-response:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nameOnCard: 
          type: string
          example: "John Doe"
        status: 
          type: string
          example: "CONFIRMADO"
        value:
          type: number
          example: "30"
        cardNumber:
          type: string
          example: "1234567812345678"
        expirationDate:
          type: string
          example: "2030-01"
        createdAt:
          type: string
          example: "2023-02-10 16:34:07"
        updatedAt:
          type: string
          example: "2023-02-10 16:34:07"
    # Orders:
    #   type: array
    #   items:
    #   $ref: "#/components/schemas/Order"


