version: "3.9"
services: 
  account:
    build: ./account/
    ports:
      - 3001:3001
    volumes:
      - ./account:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
      
  product-container:
    build: ./product/
    ports:
      - 3002:3002
    volumes:
      - ./product:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  order:
    build: ./order/
    ports:
      - 3003:3003
    volumes:
      - ./order:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  finance:
    build: ./finance/
    ports:
      - 3004:3004
    volumes:
      - ./finance:/app-node
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql

  mongodb:
    container_name: mongo-ecomm
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"

  mysql:
    container_name: mysql-ecomm
    image: mysql
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - db-mysql-ecomm:/var/lib/mysql

volumes:
  db-mongo-ecomm:
  db-mysql-ecomm:
