version: "3.9"
services: 
  account:
    build: ./account/
    ports:
      - 3001:3001
    volumes:
      - ./account:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
      - redis
      
  product:
    build: ./product/
    ports:
      - 3002:3002
    volumes:
      - ./product:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  order:
    build: ./order/
    ports:
      - 3003:3003
    volumes:
      - ./order:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  finance:
    build: ./finance/
    ports:
      - 3004:3004
    volumes:
      - ./finance:/app-node
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql
      - redis

  api-gateway:
    build: ./gateway/
    ports:
      - 3000:3000
    volumes:
      - ./gateway:/app-node
    environment:
      - PRODUCT_HOST=product
      - FINANCE_HOST=finance
      - ACCOUNT_HOST=account
      - ORDER_HOST=order
    depends_on:
      - account
      - product
      - finance 
      - order

  mongodb:
    container_name: mongo-ecomm
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - db-mongo-ecomm:/data/db

  mysql:
    container_name: mysql-ecomm
    image: mysql
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - db-mysql-ecomm:/var/lib/mysql

  redis:
    container_name: redis-ecomm
    image: redis
    volumes:
    - redis_data:/data
    restart: always
    ports:
    - 6379:6379

volumes:
  db-mongo-ecomm:
  db-mysql-ecomm:
  redis_data:
