version: "3.9"
services: 
  account:
    build: ./account/
    ports:
      - 3001:3001
    volumes:
      - ./account:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb
      - redis
      
  product:
    build: ./product/
    ports:
      - 3002:3002
    volumes:
      - ./product:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  order:
    build: ./order/
    ports:
      - 3003:3003
    volumes:
      - ./order:/app-node
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  finance:
    build: ./finance/
    ports:
      - 3004:3004
    volumes:
      - ./finance:/app-node
    environment:
      - DB_HOST=mysql
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - mysql
      - redis

  api-gateway:
    build: ./gateway/
    ports:
      - 3000:3000
    volumes:
      - ./gateway:/app-node
    environment:
      - PRODUCT_HOST=product
      - FINANCE_HOST=finance
      - ACCOUNT_HOST=account
      - ORDER_HOST=order
    depends_on:
      - account
      - product
      - finance 
      - order

  invoice:
    build: ./invoice/
    volumes:
      - ./invoice:/app-node
    environment:
      - DB_HOST=mysql
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - kafka

  mongodb:
    container_name: mongo-ecomm
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - db-mongo-ecomm:/data/db

  mysql:
    container_name: mysql-ecomm
    image: mysql
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d
      - db-mysql-ecomm:/var/lib/mysql

  redis:
    container_name: redis-ecomm
    image: redis
    volumes:
    - redis_data:/data
    restart: always
    ports:
    - 6379:6379

  zookeeper:
    container_name: zookeeper-ecomm
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    container_name: kafka-ecomm
    image: bitnami/kafka
    ports:
      - 9092:9092
    # volumes:
    # - kafka-persistence:/bitnami/kafka
    restart: always
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  db-mongo-ecomm:
  db-mysql-ecomm:
  redis_data:
  # kafka-persistence:
