openapi: 3.0.3
info:
  title: Ecomm - Product
  description: API para controle de produtos do Ecomm
  version: 0.0.1
paths:
  /api/categories:
    get:
      summary: Retorna todas as categorias cadastradas.
      responses: 
        200: 
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
        404:
          description: Nenhuma categoria cadastrada
          content:
            application/json:
              example: "Not Found"
  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      summary: Recupera uma categoria pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Categoria n達o encontrada.
          content:
            application/json:
              example: "Not Found"
  /api/admin/categories:
    post:
      summary: Cria uma nova categoria.
      requestBody:
        content:
          application/json:
            schema:   
              type: object
              properties:
                categoryName: 
                  type: string
      responses:
        201: 
          description: Categoria criada com sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    put:
      summary: Atualiza uma categoria.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        200:
          description: Categoria atualizada com sucesso!
  /api/admin/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    patch:
      summary: Ativa uma categoria.
      responses:
        200:
          description: Categoria ativada com sucesso!
    delete:
      summary: Deleta uma categoria.
      responses:
        200:
          description: Categoria apagada com sucesso!
  /api/products:
    get:
      summary: Retorna todos os produtos cadastrados.
      responses: 
        200: 
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        404:
          description: Nenhum produto cadastrado
          content:
            application/json:
              example: "Not Found"
  /api/products/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    get:
      summary: Busca um produto por ID.
      responses:
        200:
          description: Sucesso!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        404:
          description: Produto n達o encontrado.
  /api/admin/products:
    post:
      summary: Cadastra um novo produto.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses: 
        201: 
          description: Produto cadastrado com sucesso!
        404:
          description: ERRO! Produto n達o foi cadastrado, contate o suporte.
          content:
            application/json:
              example: "Not Found"
    put:
      summary: Altera os dados de um produto.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses: 
        201: 
          description: Produto alterado com sucesso!
        404:
          description: ERRO! Produto n達o encontrado, contate o suporte.
          content:
            application/json:
              example: "Not Found"
  /api/admin/products/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: string
      required: true
    delete:
      summary: Deleta um produto.
      responses:
        200:
          description: Produto apagado com sucesso!
components:
  schemas:
    Category:
      type: object
      properties:
        _id:
          type: string
        name: 
          type: string
        status: 
          type: boolean
    Categories:
      type: array
      items:
        $ref: "#/components/schemas/Category"
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        slug:
          type: string
        unitPrice:
          type: number
        stockQuantity:
          type: integer
        categoryId:
          type: string
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
                    