name: "product"

on:
  push:
    paths:
      - "./product/**"
      - ".github/workflows/product.yaml"
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci


      - name: Run tests
        run: |-
          cd product
          npm test
